const items = window.PORTFOLIO_ITEMS || [];
const collection = document.querySelector('#collection');
const detail = document.querySelector('#detail');
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const safeURL = value => { if (!value) return ''; try { const url = new URL(value, location.href); return ['http:', 'https:'].includes(url.protocol) ? url.href : ''; } catch { return ''; } };
function cover(item) { if(item.cover === 'island') return '<div class="island" role="img" aria-label="暴食岛的像素岛屿"></div><span class="cover-category">GLUTTONY ISLAND</span>'; if(item.type === 'document') { const docLabel = item.cover === 'resume' ? 'PERSONAL RESUME' : 'GAME DESIGN DOCUMENT'; const docTitle = item.cover === 'resume' ? '陈乐琦<br>个人简历' : '暴食岛<br>游戏策划案'; return `<div class="doc-sheet"><span>${docLabel}</span><strong>${docTitle}</strong><i></i><i></i><i></i></div><span class="doc-version">在线阅读 · PDF</span>`; } if(safeURL(item.cover)) return `<img src="${escapeHTML(safeURL(item.cover))}" alt="${escapeHTML(item.title)}" style="width:100%;height:100%;object-fit:cover">`; return '<span class="empty-symbol" aria-hidden="true">▷</span>'; }
function render(filter = 'all') { const selected = filter === 'all' ? items : items.filter(item => item.type === filter); collection.innerHTML = selected.length ? selected.map(item => `<article class="work-card"><button class="card-cover ${item.cover === 'island' ? 'game-cover' : 'doc-cover'}" data-open="${escapeHTML(item.id)}" aria-label="查看${escapeHTML(item.title)}">${cover(item)}<span class="card-arrow" aria-hidden="true">↗</span></button><div class="card-meta"><span>${escapeHTML(item.label)}</span><span>${escapeHTML(item.status)}</span></div><h3><a href="#project=${encodeURIComponent(item.id)}">${escapeHTML(item.title)}</a></h3><p>${escapeHTML(item.subtitle)}</p></article>`).join('') : '<div class="empty-state"><span class="empty-symbol" aria-hidden="true">▷</span><h3>视频作品，正在准备中</h3><p>游戏演示与开发记录将在这里与你见面。</p></div>'; }
for(const type of ['all','game','video','document']) document.querySelector(`#count-${type}`).textContent = String(type === 'all' ? items.length : items.filter(item=>item.type===type).length).padStart(2,'0');
document.querySelectorAll('[data-filter]').forEach(button => button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(other=>{other.classList.toggle('active',other===button);other.setAttribute('aria-pressed',String(other===button));});render(button.dataset.filter);}));
function openProject(id) { const item = items.find(record => record.id === id); if(!item)return; const url = safeURL(item.url); const game = item.type === 'game'; const media = game ? '<div class="feature-art dialog-art"><div class="island" role="img" aria-label="暴食岛的像素岛屿"></div></div>' : item.type === 'video' && item.kind === 'video' && url ? `<video controls playsinline preload="metadata" src="${escapeHTML(url)}"></video>` : ''; const gameDetails = game ? '<div class="detail-grid"><div><strong>经营与资源循环</strong><p>种植、采集、烹饪与上贡，让食物同时承担生存资源和成长选择。</p></div><div><strong>探索与战斗</strong><p>分支冒险路线、回合制战斗、QTE 与遗物，构成探索中的决策。</p></div><div><strong>系统设计与实现</strong><p>使用 Godot 与 GDScript，将规则、界面和配置转化为游戏原型。</p></div><div><strong>当前阶段</strong><p>项目持续开发中，完整剧情与部分系统仍在完善。</p></div></div>' : ''; document.querySelector('#detail-content').innerHTML = `${media}<h2 id="detail-title">${escapeHTML(item.title)}</h2><div class="tags"><span>${escapeHTML(item.label)}</span><span>${escapeHTML(item.status)}</span></div><p>${escapeHTML(item.description)}</p>${gameDetails}<div class="detail-actions">${game ? '<a class="primary" href="assets/gluttony-design-v2.docx" download>下载游戏策划案 ↓</a>' : ''}${url ? `<a class="${game ? 'secondary' : 'primary'}" href="${escapeHTML(url)}" ${item.kind === 'link' ? 'target="_blank" rel="noopener noreferrer"' : 'download'}>${item.kind === 'link' ? '打开视频页面 ↗' : game ? '下载游戏 ↓' : item.type==='video' ? '下载视频 ↓' : '下载文档 ↓'}</a>` : game ? '<span class="unavailable">游戏安装包暂未提供</span>' : ''}</div>`; if(!detail.open)detail.showModal();document.body.classList.add('modal-open'); }
document.addEventListener('click',event=>{const button=event.target.closest('[data-open]');if(button)openProject(button.dataset.open);});
document.querySelector('#close-detail').addEventListener('click',()=>detail.close());
detail.addEventListener('click',event=>{if(event.target === detail){const bounds=detail.getBoundingClientRect();if(event.clientX<bounds.left||event.clientX>bounds.right||event.clientY<bounds.top||event.clientY>bounds.bottom)detail.close();}});
detail.addEventListener('close',()=>{document.body.classList.remove('modal-open');detail.querySelector('video')?.pause();if(location.hash.startsWith('#project='))history.replaceState(null,'',location.pathname+location.search+'#works');});
function checkHash(){if(location.hash.startsWith('#project=')){try{openProject(decodeURIComponent(location.hash.slice(9)));}catch{}}}
window.addEventListener('hashchange',checkHash);document.querySelector('#year').textContent = new Date().getFullYear();render();checkHash();
